CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    price       DECIMAL(10, 2)                          NOT NULL,

    -- nếu không nhập thì mặc định là 0
    stock       INTEGER                                 NOT NULL DEFAULT 0,
    image_url   VARCHAR(255),

    -- khoá ngoại liên kết đến bẳng categories
    -- dùng bigint để cùng kiểu dữ liệu với cột id khoá chinh của bẳng categories
    category_id BIGINT,

    -- CONSTRAIN (bắt buộc) tạo mối quan hệ liên kết với khoá ngoại
    CONSTRAINT fk_products_categories FOREIGN KEY (category_id) REFERENCES categories (id),

    created_at  TIMESTAMP                                        DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP                                        DEFAULT CURRENT_TIMESTAMP
);

